// let L = prompt("sonkirit")
// let meters = Math.floor(L / 100);
// console.log("To‘liq metrlar soni:", meters);
// let M = parseInt(prompt("Og‘irlikni kilogrammda kiriting:"));
// let tons = Math.floor(M / 1000);
// console.log("To‘liq tonnalar soni:", tons);
// let bytes = parseInt(prompt("Fayl hajmini baytlarda kiriting:"));
// let kilobytes = Math.floor(bytes / 1024);
// console.log("To‘liq kilobaytlar:", kilobytes);
// let A = parseInt(prompt("A ni kiriting (A > B):"));
// let B = parseInt(prompt("B ni kiriting (B < A):"));
// let count = Math.floor(A / B);
// console.log("B kesma A kesmada", count, "marta joylashgan");
// let num = parseInt(prompt("Ikki xonali son kiriting:"));
// let tens = Math.floor(num / 10);
// let ones = num % 10;
// console.log("O‘nliklar:", tens, "Birlar:", ones);
// let num = parseInt(prompt("Ikki xonali son kiriting:"));
// let a = Math.floor(num / 10);
// let b = num % 10;
// let reversed = b * 10 + a;
// console.log("Almashtirilgan son:", reversed);